services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin5
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  pgvector_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local